### ISSUE TITLE
Reading Stream in a loop

### ISSUE THREAD

**Issue by atambi802** [pothosware/go-soapy-sdr#3]
Hello!

I am trying to constantly stream the buffer using a loop, and the buffer needs to be set before. So there is a limit on how long it can ever be right? Because the moment the buffer is smaller then infinite time, and it will just hang waiting for the buffer size, and prevent the buffer from overflowing.

Thanks!

**Comment by zuckschwerdt** [comment]
Keywords to read up on regarding buffering: double buffering, ring buffer /circular buffer.

**Comment by atambi802** [comment]
This is something with actually thinking about it, thanks! Just used a for loop, and some basic channels
